---
- name: add redo
  template:
    src:  templates/virt7-docker-common-release.repo.j2
    dest: /etc/yum.repos.d/virt7-docker-common-release.repo
    owner: root
    group: root
    mode: 777
- name: Installing the kubernetes packages on all nodes
  yum: name="{{ item }}" state=latest update_cache=yes
  with_items: "{{ packages_list }}"

- name: Disable firewall
  service: name=firewalld state=stopped enabled=no
  ignore_errors: true

- name: Disable selinux
  selinux: state=disabled
  ignore_errors: true
